site_name: Lexicons
repo_name: 'lexicons-website'
repo_url: 'https://github.com/technopreneurg/lexicons-website'

theme:
  name: material
  palette:
    primary: 'deep purple'
    accent: 'purple'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-102723231-2', 'auto']

markdown_extensions:
  - meta

pages:
- Home: index.md
- Lexicons-*:
    - lexicon-aws.md
    - lexicon-artificial-neural-networks.md
    - lexicon-cloud-computing.md
    - lexicon-computational-linguistics.md
