site_name: Lexicons
repo_name: 'lexicons-website'
repo_url: 'https://github.com/technopreneurg/lexicons-website'

theme: 'material'
extra:
  palette:
    primary: 'deep purple'
    accent: 'purple'

google_analytics: ['UA-102723231-2', 'auto']

pages:
- Home: index.md
- Lexicons-*:
    - Artificial Neural Networks: lexicon-artificial-neural-networks.md
    - Computational Linguistics: lexicon-computational-linguistics.md
