site_name: Lexicons
repo_name: 'my-github-handle/my-project'
repo_url: 'https://github.com/my-github-handle/my-project'
#theme: readthedocs
#theme: spacelab

theme: 'material'
extra:
  palette:
    primary: 'deep purple'
    accent: 'purple'

# Extensions
#markdown_extensions:
#  - admonition
#  - codehilite(guess_lang=false)
#  - toc(permalink=true)

pages:
- Home: index.md
- Lexicons-*:
    - Artificial Neural Networks: lexicon-artificial-neural-networks.md
    - Computational Linguistics: lexicon-computational-linguistics.md
